/** @format */

import type { Metadata } from "next";
import { Inter, Suez_One } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"],  variable: '--font-inter',
});
const suez = Suez_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-suez",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${suez.variable} bg-background min-w-[350px]`}
        suppressHydrationWarning
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
